services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    restart: always
