FROM golang:1.23

WORKDIR /app

# Copy go mod files first for better caching
COPY go.mod go.sum ./
RUN go mod download

# Copy all files
COPY . .

# Build the application
RUN go build -o api-app ./cmd/api

# Copy .env to the root of the app directory
COPY cmd/api/.env .

EXPOSE 8081
CMD ["./api-app"]